### ISSUE TITLE
Error in update-mirrorlist when installing Online Mode

### ISSUE THREAD

**Issue by MS-Jahan** [CachyOS/CachyOS-Live-ISO#16]
Here is the log:
https://termbin.com/2dk8

**Comment by vnepogodin** [comment]
Already fixed (https://github.com/CachyOS/cachyos-calamares/commit/9ffbf4991ae76023b29aef8c1fe9c7affa5e44e9) week ago

**Comment by ptr1337** [comment]
We will bring a fixing release on the weekend
