### ISSUE TITLE
CachyOS-Live-ISO build failing

### ISSUE THREAD

**Issue by cynman** [CachyOS/CachyOS-Live-ISO#18]
Ideas?  Thanks you for your time.

install: cannot stat '/data/cachyos-archiso/build/x86_64/airootfs/usr/share/licenses/common/GPL2/license.txt': No such file or directory
mv: cannot stat '/data/cachyos-archiso/out/kde/cachyos-2024.01.20-x86_64.iso': No such file or directory
==> Done [Build ISO] cachyos-kde-linux-240120.iso
==> Finished building [kde]
 --> Time run_build: 5.27 minutes

**Comment by lseman** [comment]
Yes, it is a known bug in archiso, already patched dev git but not updated in mainline repositories.
I'll get the link.

**Comment by ptr1337** [comment]
> Ideas? Thanks you for your time.
> 
> install: cannot stat '/data/cachyos-archiso/build/x86_64/airootfs/usr/share/licenses/common/GPL2/license.txt': No such file or directory mv: cannot stat '/data/cachyos-archiso/out/kde/cachyos-2024.01.20-x86_64.iso': No such file or directory ==> Done [Build ISO] cachyos-kde-linux-240120.iso ==> Finished building [kde] --> Time run_build: 5.27 minutes

You need to fetch the mkarchiso script from upstream and replace it with the one locally.
Anyways, I build yesterday a ISO for the upcoming release:
https://mirror.cachyos.org/ISO/testing/

This has been tested so far and we are waiting just for a little change on the hardware detection.

**Comment by cynman** [comment]
Wow, thank you Iseman / ptr1337 for the quick replies.  Appreciated.
