### ISSUE TITLE
cachyos-2022.05.09-x86_64 not booting

### ISSUE THREAD

**Issue by Anonymo** [CachyOS/CachyOS-Live-ISO#2]
![cachyOS](https://user-images.githubusercontent.com/967787/167757349-fe09f23f-43fd-4f22-9522-0daa6e83fad5.jpg)

I'm getting this error on 2 machines.

A desktop with a b450 tomahawk max, set to UEFI only, safeboot off and nVidia graphics card.
Second machine is a Thinkpad T440p with only Intel graphics.

I'm using Ventoy to try to boot, works with other distros like LMDE5.

Also tried the cachyos-kde-linux-220509.iso

**Comment by ptr1337** [comment]
Hey! 

Thanks for your report! We are working currently much on the ISO, it still has some issue's. But most seems to be fixed.

Will notify with the upcoming iso

Reards.

**Comment by Anonymo** [comment]
> Hey!
> 
> Thanks for your report! We are working currently much on the ISO, it still has some issue's. But most seems to be fixed.
> 
> Will notify with the upcoming iso
> 
> Reards.

Hello
The latest commits to this for today (5/14) have made it so the ISO boots.  I was able to create the ISO using EndevourOS.  Nice.  Loving the default Plasma theme.

I tested out the installer for a ZFS install and the option for ZFS + swap file failed.
I tested the ZFS + swap partition (hibernate) and it got further along but eventually hit these errors:
https://termbin.com/y8qn

I'm know you guys have this as a work in progress but wanted to update with the testing I've done on my T440p Intel only.

**Comment by ptr1337** [comment]
Hey! 
I already createt a ISO but actually I got the issue when installing, everything wents fine. It does his pacstrap online install, as soon want to install the custom packages, pacman fails with 'pacman -Sy'. 

And it shows that the mirrors are not available. I think that problem should be also sloved soon and then the iso got a very big step forward.

For the zfs issue we have already a solution and will be soon pushed. I think its better if we push a mostly stable iso before building somehow a own one. The zfs support is not in progress, the complete installation, kernels and userspace is completly tested. We just switched to another backend (pacstrap) to provide a way more cleaner netinstall.
Thanks for your testing.

I will upload a last built iso from me which went fine in a VM but in my userspace it failed.

Could be a DNS resolution error from my internet connection / router or a bug in the iso. We need to watch. 

Regards,

**Comment by ptr1337** [comment]
@Anonymo 
Could you checkout this iso? 
https://cloud.ptr1337.dev/s/PiZ8ySsywnjTnGe

zfs needs some fixes but so far it does a fine job. So avoid using zfs as filesystem for now. I did two live uefi installs and everything went fine! Also in a vm i faced no issue's.

Thanks for testing

**Comment by Anonymo** [comment]
Thank you.

Yes, this one booted and installed with BTRFS.

**Comment by ptr1337** [comment]
> Thank you.
> 
> Yes, this one booted and installed with BTRFS.

Great, ive included a zfs fix which should fix the described issue above, but I need to test that. 

But so far the iso seems stable.

Are you faced into any other issue's or have something which we could improve ?  ?

**Comment by Anonymo** [comment]
No issues so far. 

Maybe if it's not too hard to implement, add for BTRFS a setup Snapper setup.  Could probably be copied from Garuda and for ZFS there is either ZFSbootmenu

https://github.com/zbm-dev/zfsbootmenu

or Sanoid

https://github.com/jimsalterjrs/sanoid

**Comment by ptr1337** [comment]
@Anonymo 
Great! Glad to hear. We are doing currently some fine tuning and then we will release the iso. 
We are implementing for btrfs snapper or timeshift? Snapper would be probably the better idea. Also "btrfs-assistant" will be implemented for btrfs.

Actually zfsbootmenu is hard to implement since its calamares based, that would be a option for the cli installer. 
Actually we are forced to use with the gui installer to grub, maybe with a manual zpool creation that would be possible.

Also the encryption wont be possible with zfs currently. But looking forward into the future, thanks for the feedback.

**Comment by ptr1337** [comment]
The stable release just where today! If you want you can run again a test install, but so far everything should be fine! 
Thanks alot for your testing.

https://forum.cachyos.org/d/34-cachyos-gui-installer-stable-release
