### ISSUE TITLE
Live ISO error: lightdm failed to start

### ISSUE THREAD

**Issue by Matgen84** [CachyOS/CachyOS-Live-ISO#24]
Hi

A few minutes ago, I've  build CachyOS Live ISO successfully. When I boot from Ventoy USB key:

-  error failed to start Lightdm.service and stuck at graphical interface (searching synchronize...)

No problem with Arch with ArchISOMaker.

Any solutions, please.

Thanks

**Comment by ptr1337** [comment]
> Hi
> 
> A few minutes ago, I've build CachyOS Live ISO successfully. When I boot from Ventoy USB key:
> 
> * error failed to start Lightdm.service and stuck at graphical interface (searching synchronize...)
> 
> No problem with Arch with ArchISOMaker.
> 
> Any solutions, please.
> 
> Thanks

We do not support building the ISO with other Desktop Envorments, only KDE is supported.

**Comment by ptr1337** [comment]
You can find precompiled ISOs on the website/mirrors.

**Comment by Matgen84** [comment]
Thanks for reply.

I can't install pre-compiled Cachyos KDE : stuck at graphical interface (kernel synchro time). Of with nomodeset arg.

My old config is: core i7 3770k, Asus P8z77-v Pro, Nvidia GT640 (Kepler).

**Comment by ptr1337** [comment]
> Thanks for reply.
> 
> I can't install pre-compiled Cachyos KDE : stuck at graphical interface (kernel synchro time). Of with nomodeset arg.
> 
> My old config is: core i7 3770k, Asus P8z77-v Pro, Nvidia GT640 (Kepler).

Try the testing ISO:
https://mirror.cachyos.org/ISO/testing/

Anyways, the super old NVIDIA graphics are generally very badly supported at linux. Either try the nomodeset or default option, so that it will load the kernel driver.

**Comment by Matgen84** [comment]
I try and report.

**Comment by Matgen84** [comment]
I can't boot Testing ISO : stuck at Reached Graphical Interface, Wait Kernel synchro... At 5 minutes, I stop the process and reboot.
Strange !
