### ISSUE TITLE
Add support for a Gnome Live ISO

### ISSUE THREAD

**Issue by rayzorben** [CachyOS/CachyOS-Live-ISO#29]
I understand the cost and maintenance and time involved in maintaining multiple Live ISO's. However, although Windows users might prefer a KDE enviroment that they can use to try out Cachy, and it's a great introduction for them, there are countless many other users coming from Ubuntu or the other many distros that default to Gnome out of the box that don't want to feel like they are in Windows and are more comfortable with Gnome tools than KDE.

**Comment by ptr1337** [comment]
We really deprecated it, because we never maintained the Gnome ISO. Also, no one in the team had time for doing this.

People can test in a VM, if they want to. The ISO is generally very stripped and not thought for live testing.
