### ISSUE TITLE
Fix automounting from kde plasma

### ISSUE THREAD

**Issue by ptr1337** [CachyOS/CachyOS-Live-ISO#3]
Their is a possbility to prevent the automounting from Plasma, which actually does the bug that ZFS filesystems are automatically mount and the iso is not use able for people which already have a zfs filesystem installed

**Comment by vnepogodin** [comment]
related https://github.com/CachyOS/CachyOS-Live-ISO/commit/d8b34d66f6ad34f17a286f4f01759f1024465d64

**Comment by ptr1337** [comment]
fixed by https://github.com/CachyOS/CachyOS-Live-ISO/commit/9bb8fa48e91d70a2586963ad513882a54497dd7d
