### ISSUE TITLE
Cachyos 24.09 chwd install error Rx 6700xt R5 3600

### ISSUE THREAD

**Issue by TIMW2020** [CachyOS/CachyOS-Live-ISO#31]
https://termbin.com/aoxj

**Comment by ptr1337** [comment]
Huh, this is the testing ISO, or?

**Comment by TIMW2020** [comment]
Yeah, latest commit build and try install

**Comment by ptr1337** [comment]
> Yeah, latest commit build and try install

Oh, wait. You did build it on your own. Let me fastly push some fixes.

**Comment by ptr1337** [comment]
https://github.com/CachyOS/CachyOS-Live-ISO/commit/45f70fe70c555b7aa746a875714a33b6811682f5

Should be fixed by that. You need to rebuild the ISO.
The 24.09 release is also not fully done yet, ive just added some changelogs so far, but we will not plan to release till 21.09.

**Comment by TIMW2020** [comment]
Great i will go for it thx
