### ISSUE TITLE
Installer silently closing on 2024-11 ISO

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/CachyOS-Live-ISO#38]
Hi,

I got the latest image from 2024-11. And for whatever reason when I click to Launch the Installer on the Hello window, it closes the hello and does not open the installer. 

---

Edit: After a few tries, it did open. 

It did have a similar but different behavior before, not sure if it was dependant on internet connection or what.

**Comment by vnepogodin** [comment]
> Hi,
> 
> I got the latest image from 2024-11. And for whatever reason when I click to Launch the Installer on the Hello window, it closes the hello and does not open the installer.

Hi @dougg0k,

Can you close everything, start the hello from terminal, press launch installer and show what it outputs in the terminal

**Comment by dougg0k** [comment]
Now it did but with the error i mentioned.

![20241123_161832.jpg](https://github.com/user-attachments/assets/79de0a0c-0483-428b-9cdb-f9695fb58687)

**Comment by dougg0k** [comment]
Got it.

![20241123_162440.jpg](https://github.com/user-attachments/assets/7350d70e-475f-48d3-afef-f35a499ba18f)

**Comment by vnepogodin** [comment]
> Got it.
> 
> ![20241123_162440.jpg](https://private-user-images.githubusercontent.com/10801221/389221789-7350d70e-475f-48d3-afef-f35a499ba18f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzOTAyODYsIm5iZiI6MTczMjM4OTk4NiwicGF0aCI6Ii8xMDgwMTIyMS8zODkyMjE3ODktNzM1MGQ3MGUtNDc1Zi00OGQzLWFmZWYtZjM1YTQ5OWJhMThmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE5MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MmE4OWZjZmU1ZjMyMWQ4MGZiMjVkY2UwYzYyNWFkNTg2NWVkODljYTk2ZTIwNWYzMmNkOTcyNmQ5NTMwZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fl6QhfbrDGLJH5mHEawddWpbBNXTSnD3o2n7-nCbVi0)

hmm we can add retries, but it wont help with internet connection. maybe your ISP is blocking Cloudflare or Cloudflare is blocking you :smiley:

**Comment by dougg0k** [comment]
It surely isnt. Before nextdns, I used cloudflare.
