### ISSUE TITLE
pacman running out of space in Copy-to-RAM installation mode

### ISSUE THREAD

**Issue by Skalt711** [CachyOS/CachyOS-Live-ISO#5]
pacman downloads base packages to cowspace, which has 256MB allocated in Copy-to-RAM mode. Unfortunately pacman downloads the total sum of packages weighing more than the space cowspace is allocated for, which means that installer will fail at some point. In my case cowspace has grown to 655MB, then the rest of packages was downloaded to the root partition directly.

The installer has no issue with space in normal (non-Copy-to-RAM) mode, which has 5GB allocated.

I suggest to set the cowspace size to 1GB. It means the minimum RAM requirement for CachyOS to be 2GB (In normal mode. Copy-to-RAM would likely require 4GB) and pacman's lack of space problem solved.

I use the Live image from 23rd June.

**Comment by ptr1337** [comment]
The issue seems to be here through the missing cowspace.
https://github.com/CachyOS/CachyOS-Live-ISO/blob/master/archiso/grub/grub.cfg#L43

We will fix it with the next release, thanks for the report!

**Comment by ptr1337** [comment]
https://github.com/CachyOS/CachyOS-Live-ISO/commit/9cc125cfd45e3b8e80bd720714c7df30b8b2559a

Should be fine with that commit
