### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by xstefen** [CachyOS/CachyOS-Live-ISO#8]
2022-09-22 - 21:46:13 [6]: [PYTHON JOB]: "error: target not found: ipw2200-fw" 

https://termbin.com/c85j

**Comment by ptr1337** [comment]
> 2022-09-22 - 21:46:13 [6]: [PYTHON JOB]: "error: target not found: ipw2200-fw"
> 
> https://termbin.com/c85j

Thanks for the issue. It seems arch has removed this package out of there repo's.
The issue has been fixed for the online installation.
The offline installation should work anyways.

https://github.com/CachyOS/calamares-config/commit/fa5f7f9b2114a56828cfae724947caf49aecaa4f

https://github.com/CachyOS/calamares-config/commit/fa5f7f9b2114a56828cfae724947caf49aecaa4f
